# Generated by Django 4.0.4 on 2022-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('ModuleId', models.AutoField(primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(max_length=100)),
                ('ModuleCode', models.CharField(default='test', max_length=10)),
                ('ModuleLecturer', models.CharField(default='test', max_length=50)),
            ],
        ),
    ]
