# Generated by Django 4.0.4 on 2022-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ClassId', models.AutoField(primary_key=True, serialize=False)),
                ('ClassType', models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial')], default='Lecture', max_length=10)),
                ('ClassDay', models.CharField(max_length=10)),
                ('ClassStartTime', models.CharField(max_length=10)),
                ('ClassEndTime', models.CharField(max_length=10)),
                ('ClassLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='modules',
            name='ModuleCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ModuleLecturer',
            field=models.CharField(max_length=50),
        ),
    ]
