# Generated by Django 4.0.4 on 2022-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0003_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='ModuleId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
