# Generated by Django 4.0.4 on 2022-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0004_chapters_moduleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=100)),
                ('TaskStatus', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('TaskType', models.CharField(choices=[('Class', 'Class'), ('Tutorial', 'Tutorial')], default='Class', max_length=10)),
                ('ChapterId', models.IntegerField()),
            ],
        ),
    ]
