# Generated by Django 4.0.4 on 2022-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0006_modules_modulestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='ModuleGrade',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
