# Generated by Django 4.0.4 on 2022-05-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0008_tasks_taskduedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
