# Generated by Django 4.0.4 on 2022-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0011_remove_modules_modulelecturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentId', models.AutoField(primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(max_length=100)),
                ('AssessmentDate', models.DateField(default='2022-05-21')),
                ('AssessmentType', models.CharField(choices=[('Assignment', 'Assignment'), ('Test', 'Test')], default='Assignment', max_length=15)),
                ('AssessmentDetails', models.CharField(max_length=1000)),
                ('AssessmentGrade', models.CharField(max_length=2)),
                ('AssessmentStatus', models.CharField(choices=[('Due', 'Due'), ('Done', 'Done')], default='Due', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='TaskDueDate',
            field=models.DateField(default='2022-05-21'),
        ),
    ]
