# Generated by Django 4.0.4 on 2022-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0013_rename_assessment_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='ModuleName',
        ),
        migrations.AddField(
            model_name='assessments',
            name='ModuleId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessments',
            name='AssessmentDate',
            field=models.DateField(default='2022-05-22'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='TaskDueDate',
            field=models.DateField(default='2022-05-22'),
        ),
    ]
