# Generated by Django 4.0.4 on 2022-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0014_remove_assessments_modulename_assessments_moduleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='AssessmentName',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
