# Generated by Django 4.0.4 on 2022-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0015_assessments_assessmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='AssessmentGrade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
