# Generated by Django 4.0.4 on 2022-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0016_alter_assessments_assessmentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='AssessmentGrade',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
