# Generated by Django 4.0.4 on 2022-05-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStudyPlanAPI', '0017_alter_assessments_assessmentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='ModuleId',
        ),
        migrations.AddField(
            model_name='assessments',
            name='ModuleColor',
            field=models.CharField(default='#0dafe0', max_length=50),
            preserve_default=False,
        ),
    ]
